# -*- coding: utf-8 -*-
"""Copy of Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g29RkxFCeQAuaagkialGNMX8xwUDMYgl
"""

import tweepy
import json
import datetime

consumer_key = "oUuA3LWQMTqOThut1cOdwVJoU" 
consumer_secret = "Yerc0QdZCinqzR5stIHvt4kJt7waNLHGAaOGzWU67aFRMyUe1s"
access_key = "1114942545006485504-lfXVPxeRCAqq4Kj87U2prtlbdz2fkA"
access_secret = "1hr1HkPPeCVqKm2lWNgK3ZL9hdlrMUXsZPohbTkTxwk0S"

def myconverter(o):
    if isinstance(o, datetime.datetime):
        return o.__str__()
def get_tweets(username): 
          
        auth = tweepy.OAuthHandler(consumer_key, consumer_secret) 
  
        auth.set_access_token(access_key, access_secret) 
  
        api = tweepy.API(auth) 
  
         
        number_of_tweets=200
        tweets = api.user_timeline(screen_name=username) 
  
        
        outtweets = [[tweet.id_str, tweet.created_at, tweet.text, tweet.favorite_count, tweet.retweet_count,'None'] for tweet in tweets]
  
       #with open(CSV_PATH, 'r') as csv_file:
        # reader = csv.DictReader(csv_file)
        with open('demo.json', 'w') as json_file:
          for row in outtweets:
            json_file.write(json.dumps(row,default = myconverter))
          print(outtweets)

get_tweets("@midasIIITD")

